### ISSUE TITLE
add link to base16 themes?

### ISSUE THREAD

**Issue by evanrichter** [Vector35/community-themes#16]
I ported the base16 color framework to binja a while back. would this be welcome as a link on this page?

[base16-binary-ninja](https://github.com/evanrichter/base16-binary-ninja)

**Comment by jv35** [comment]
Yes, we can definitely add it. We've been waiting on some UI updates so we can redo all the screenshots at once; we should be able to update the community theme page this week. Thank you for sharing!

**Comment by plafosse** [comment]
Done
