### ISSUE TITLE
Add to README instruction on how to select theme 

### ISSUE THREAD

**Issue by luke-goddard** [Vector35/community-themes#30]
I'm trying out BN for the first time so I'm probably using it wrong. 

```
Command + P 
> theme...
```

Shows `refresh theme` but no 'select/change theme'. Also I cannot find any options in `file, edit, view, ...` either.

**Comment by luke-goddard** [comment]
Figured it out. 

```
Command + P
> settings
``` 
Then `UI` -> `Theme`

**Comment by jonpalmisc** [comment]
Added a note to the README.
